
server:
    port: 9090
    context-path: #/liuzh/

logging:
    level:
        com.thothinfo: TRACE

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/test?useSSL=false
        username: root
        password: liqiulin
        driver-class-name: com.mysql.jdbc.Driver
    h2:
        console:
            enabled: true
            path: /h2-console


mybatis:
    type-aliases-package:  org.pf9.pangu.sample.mybatis.entity
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - org.pf9.pangu.sample.mybatis.util.BaseMapper
    not-empty: false
    identity: H2

pagehelper:
    helperDialect: h2
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql